image: bradrydzewski/python:2.7
env:
  - GOROOT=/usr/local/go
  - GOPATH=$PWD/Godeps/_workspace:/var/cache/drone
  - PATH=$PWD/Godeps/_workspace/bin:/var/cache/drone/bin:$PATH
script:
  - sudo apt-get -y install libsqlite3-dev sqlite3 1> /dev/null 2> /dev/null

